apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: mlops-project1
  endpoints:
    - port: http
      path: /metrics
      interval: 15s