name: Build and Deploy Heart Disease API

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # Allows manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ====================== AUTHENTICATE TO GCP ======================
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      # ====================== BUILD DOCKER IMAGE ======================
      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "Building image with tag: $IMAGE_TAG"
          
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-project1:$IMAGE_TAG -f Dockerfile.api .
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-project1:$IMAGE_TAG gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-project1:latest

      # ====================== PUSH DOCKER IMAGE ======================
      - name: Push Docker Image to GCR
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "Pushing image with tag: $IMAGE_TAG"
          
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-project1:$IMAGE_TAG
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-project1:latest

      # ====================== DEPLOY TO GKE ======================
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: mlops-standard-cluster1
          location: us-central1-a
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "Deploying image with tag: $IMAGE_TAG"

          # Apply latest manifests (in case there are changes in deployment.yaml or service.yaml)
          kubectl apply -f k8s/deployment.yaml --server-side --force-conflicts
          kubectl apply -f k8s/service.yaml

          # Update the image in the deployment
          kubectl set image deployment/mlops-project1 \
            mlops-project1=gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-project1:$IMAGE_TAG -n default

          # Wait for rollout to complete
          kubectl rollout status deployment mlops-project1 -n default